### PR TITLE
User/le2tang/combine front rear laser scan

### PR DESCRIPTION
**Pull request by le2tang**
Removes the local version of ira_laser_tools which has a bug allowing only 1 laser scan topic to be subscribed to. The apt installed version has the bug fix

This change also requires the following to be run on the movo computers:
`sudo apt-get install ros-noetic-ira-laser-tools`

### CODE REVIEW

**Comment by FelixKHWong** [comment]
so was the current(and to be removed) version of the code copy-pasted into the repo from kinova? And so the ROS package install updates the configs and places the files in the correct place?

**Comment by le2tang** [comment]
> 

Yes, I have tested removing this directory, installing the package from apt, then running catkin build and clean. From what I understand the build system then does not need to build the ira_laser_tools, and the launch files use the ira_laser_tools files from the directory that apt installs the package into.

**Review by FelixKHWong — DISMISSED** [review]

**Review by younesr1 — DISMISSED** [review]

**Comment by younesr1** [comment]
can we mege this please @le2tang ? just sqaush and fix conflicts

**Review by FelixKHWong — APPROVED** [review]

**Comment by younesr1** [comment]
@le2tang can u merge this in?

**Pull request merged**
