### PR TITLE
Nightingale

### PR DESCRIPTION
**Pull request by FelixKHWong**
Starting the new branch for nightingale specific code. Refer to this https://github.com/nightingale-project/kinova-movo/pull/38  for more details.
This PR contains the bin urdf changes and the init removal

### CODE REVIEW

**Review by younesr1 — COMMENTED** [review]
can you share screenshots please?
also this PR targets master. we dont want that right? ill set up branch protection rules for nightingale branch so ppl need approved PRs before they can merge

**Comment by nightingale-project** [comment]
ive set up branch protection rules for nightingale. pushing to nightingale will now require approval

**Comment by FelixKHWong** [comment]
yeah you're totally right that's my bad. I'll reopen the old PR and have it point to nightingale branch. I will also blow away these commits so they can be added using the PR. Ok so these changes are already in nightingale. I wasn't able to remove the commits and force push cause I don't have permission. Here's the old PR with screenshots https://github.com/nightingale-project/kinova-movo/pull/38
bin_robot_color
bin_urdf

**Comment by FelixKHWong** [comment]
Sorry I don't know why I decided to write code directly on our new branch. The code will have to stay or we redo the branch to create a PR with these bin changes.

**Pull request closed without merging**
